FROM gitpod/workspace-full

ARG DEBIAN_FRONTEND=noninteractive
ARG CY_DEPS="libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb"
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo apt-get upgrade -y
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install ${CY_DEPS} -y
RUN npx cypress install