name: Release

on:
  workflow_run:
    workflows: ["CI - build and test affected"]
    branches: [development]
    types:
      - completed
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.DEVElOPMENT_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DEVELOPMENT_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: jgcajpecsmkatlbzsstn
      VITE_SUPABASE_API_URL: ${{ secrets.DEVElOPMENT_VITE_SUPABASE_API_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.DEVElOPMENT_VITE_SUPABASE_ANON_KEY }}


  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      parallel-commands-on-agents: |
        yarn nx affected --target=deploy --parallel=3

  agents:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3