name: Deploy - Development

on:
  push:
    branches: [development]
  workflow_dispatch:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      environment-variables: >
                              SUPABASE_ACCESS_TOKEN=${{ secrets.DEVELOPMENT_SUPABASE_ACCESS_TOKEN }}
                              SUPABASE_DB_PASSWORD=${{ secrets.DEVELOPMENT_SUPABASE_DB_PASSWORD }}
                              SUPABASE_PROJECT_ID=${{ secrets.DEVELOPMENT_SUPABASE_PROJECT_ID }}
                              VITE_SUPABASE_API_URL=${{ secrets.DEVELOPMENT_VITE_SUPABASE_API_URL }}
                              VITE_SUPABASE_ANON_KEY=${{ secrets.DEVELOPMENT_VITE_SUPABASE_ANON_KEY }}
                              VITE_SUPABASE_FUNCTIONS_API_URL=${{ secrets.DEVELOPMENT_VITE_SUPABASE_FUNCTIONS_API_URL }}
                              SUPABASE_APP_ENV=development
                              NETLIFY_SITE_ID=${{ secrets.DEVELOPMENT_NETLIFY_SITE_ID}}
                              NETLIFY_AUTH_TOKEN=${{ secrets.DEVELOPMENT_NETLIFY_AUTH_TOKEN}}
                              NX_CLOUD_DISTRIBUTED_EXECUTION=false
      number-of-agents: 1
      parallel-commands: |
        yarn nx affected --target=deploy
